import {
  Smartphone,
  Headphones,
  Laptop,
  Plug,
  Speaker,
  ShoppingBag,
  Search,
  Menu,
  X,
  Trash2,
  Plus,
  Minus,
  ChevronRight,
  ArrowRight,
  Heart,
  ChevronDown,
  HardDrive,
  MemoryStick,
  Cpu,
  Router,
  Tv,
  Tablet,
  Filter,
  PlusCircle,
  User,
  Zap,
  Shirt,
  Watch,
  Camera,
} from 'lucide-react';

export const Icons = {
  smartphone: Smartphone,
  headphones: Headphones,
  laptop: Laptop,
  plug: Plug,
  speaker: Speaker,
  shoppingBag: ShoppingBag,
  search: Search,
  menu: Menu,
  close: X,
  trash: Trash2,
  plus: Plus,
  plusCircle: PlusCircle,
  minus: Minus,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  heart: Heart,
  chevronDown: ChevronDown,
  filter: Filter,
  user: User,
  flash: Zap,
  shirt: Shirt,
  watch: Watch,
  camera: Camera,
};

export const CategoryIcons: { [key: string]: React.ComponentType<{ className?: string }> } = {
  'informatique': Laptop,
  'accessoires-informatiques': Plug,
  'telephones-tablettes': Smartphone,
  't-shirt': Shirt,
  'jacket': Shirt,
  'shirt': Shirt,
  'jeans': Shirt,
  'bag': ShoppingBag,
  'shoes': Speaker, // Placeholder, find better icon
  'watches': Watch,
  'cap': Speaker, // Placeholder
};
